language: ruby
cache:
- bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: "vY39H4JozVA9TWVSU+/owXS5gX7eMoi9Rp1pFeUIN5Uj9gcYi5QDNTDvdyq9agc96IC09psD6nw7bB4pqrYNt5Zl2wnOPCxKeb2Qsbj4wtPtswTXaJSIAK+7qeyzVkuJETWZa4cQF2WRT7g9Bn4AOCr7ruWfy02F1SpHQpzTeqctLOivemkImmO6KdVpFAU77ix146FYtKZyGN9xjzE91kzLU/6Xo5zLRdq034UjurDaDB9M4zagBbN/XABxAsWz/5il+R9hL+xbHaS/YEfaJNchhA4997lIJhV34A5Wy6PnKMA+BIgrwkF+6UdTIjhj6yEPbs9DLOeP25VroamkTmE9IxrA4jRJatw3MhU3cWlT1+7pnmaccu+bVQ0QPa56xvTKItuZl11fvSTcRt+8wohDRrITiTd14gasKKVtbAj2zlHQr/mFZjCjE3MRqPV2LzyFwBCANtAxiEHttZzRZiemV1GjcZdb72EGAb+ovtt3t6eL7aqZIoDcJjRe+kwTtb6TACN508CX96GW6Yjk3nV9bW0wkS6b7jMrEUAdkvf6I/x/qbF7crCZf3Kxyx4wj9ELlPlHQhPT2+Itx7oOfTIWyokYsrjs2ox4RqJUaxL6yNWzkluSxFnMK12i3R5zs4fnGeBwSUOyqazdoGzQos9k7d21b3CNXjMmswHkfSQ="
  app: ncc-zjadliwe
  on:
    repo: returnv01d/vol3-green